### ISSUE TITLE
Message Link pings users again if they were pinged in the original message

### ISSUE THREAD

**Issue by FravBox** [BlackWolfWoof/yagpdb-cc#16]
re: https://github.com/BlackWolfWoof/yagpdb-cc/blob/master/Misc/message%20link.gotmpl

If the original message has a ping and an embed, yag recreates the message entirely, thus pinging all the users again. 
This is really only an issue with messages from the Sesh event bot. So perhaps simply ignoring messages from this user would be a solution.

Alternatively, if stripping the pings is not doable, adding a function to ignore message links in carats( e.g. how `<https://url.com>` does not create an embed in discord), that could also work.

I love this custom command... It should be included by default in yag. So thanks for making it. I hope you could fix this, though!

Thank you.

![image](https://user-images.githubusercontent.com/20410737/117516678-c7973580-af67-11eb-9788-77b9b859b893.png)

**Comment by l-zeuch** [comment]
Put simply, use the following trigger to achieve it **not** triggering with carats: (?:[^<]|\A)https://(?:\w+\.)?discord(?:app)?\.com/channels\/(\d+)\/(\d+)\/(\d+)(?:[^>\d]|\z)

Apart from that, there is no good way to prevent this from happening as of now, given by how the allowed mentions field is messages work (blame Discord).

**Comment by l-zeuch** [comment]
Just update the trigger in my opinion, is also more intuitive and simulates the behaviour Discord shows with normal links.

**Comment by BlackWolfWoof** [comment]
> Just update the trigger in my opinion, is also more intuitive and simulates the behaviour Discord shows with normal links.

But that would defeat the purpose of using message link to quote the message and display its content across channels

**Comment by BlackWolfWoof** [comment]
i'll simply just add some fix to not ping users

**Comment by l-zeuch** [comment]
> But that would defeat the purpose of using message link to quote the message and display its content across channels

How would that defeat the purpose?
With a normal link, say, `https://youtube.com` Discord will embed it, unless we enclose it in carets like so: `<https://youtube.com>`. 
The new and updated trigger will exactly simulate that kind of behaviour, making it more intuitive than always embedding the message.

**Comment by FravBox** [comment]
The best case scenario is add a fix to not ping users and also keeping the modified trigger. The carats do allow some extra control from users. There are times when you want to link to a message and not initiate a preview from yag.

**Comment by l-zeuch** [comment]
Works perfectly fine on my end...
You aren't hitting custom command limits (3 per event)?

**Comment by l-zeuch** [comment]
P.S.: Sounds more like a code issue to me, try using the latest code if you aren't already.

**Comment by FravBox** [comment]
Ended up being something completely different - #19

**Comment by BlackWolfWoof** [comment]
Note to myself: Use .Message.Mentions and getMember everyone and check if they are still on the server
