### ISSUE TITLE
dbResetKey

### ISSUE THREAD

**Issue by Dhmee** [BlackWolfWoof/yagpdb-cc#25]
![image](https://user-images.githubusercontent.com/31671759/126646936-7863586f-6cea-4351-b573-fb5cf3a9d448.png)

**Comment by BlackWolfWoof** [comment]
If you are not using the official YAGPDB bot then update the selfhost

**Comment by BlackWolfWoof** [comment]
If you cannot update the selfhost tho you have to stick to the old code from now on until you update it
