### ISSUE TITLE
Antiraid script for new users during nighttime?

### ISSUE THREAD

**Issue by maikelopstraat** [BlackWolfWoof/yagpdb-cc#37]
Hello is it possible in a way that the antiraid scipt can be used for new users during nighttimes?

**Comment by BlackWolfWoof** [comment]
Sorry for the late reply. I am currently trying to catch up a bit with the backlog.
You could disable the code during "nighttimes" (timezones exist and spammers don't care). That would require you to get the current time where you live (that is possible) and then check if it is bewteen the 2 times you'd like it to run.

But i do not recommend doing that, as spammers can just launch the attack whenever they want and at whatever time they want. Also timezones are a thing so uhhhh yea.
