### ISSUE TITLE
Video at link in FakeBan removed from YouTube.

### ISSUE THREAD

**Issue by Moleculor** [BlackWolfWoof/yagpdb-cc#39]
https://github.com/BlackWolfWoof/yagpdb-cc/blob/master/Misc/fakeban.yag#L20

The link you click on to get "Logs" in the FakeBan command leads to a video removed from YouTube. 

Not the most dramatic of issues, but I figured I'd point it out.

**Comment by l-zeuch** [comment]
PR'd a fix in #40
