### ISSUE TITLE
Add setcount to the uhhh thing... readme :)

### ISSUE THREAD

**Issue by BlackWolfWoof** [BlackWolfWoof/yagpdb-cc#45]
exactly what the title says

**Comment by kass507** [comment]
when using the command it sends this.
![imagen](https://user-images.githubusercontent.com/74341018/147199259-cfd77307-b07f-4454-ab79-787c295d3edd.png)

**Comment by BlackWolfWoof** [comment]
Ah, i forgot to remove the debug output from the setcount code hehe @kass507

**Comment by BlackWolfWoof** [comment]
I pushed a fix for it now

**Comment by galen8183** [comment]
Worthy of note: This issue is resolved by #49

**Comment by BlackWolfWoof** [comment]
resolved by #49
