### ISSUE TITLE
An error caused the execution of the custom command template to stop.

### ISSUE THREAD

**Issue by choccy-dev** [BlackWolfWoof/yagpdb-cc#48]
"Failed executing CC #12, line 73, row 19: executing "CC #12" at <exec "kick" $userid ...>: error calling exec: exec/execadmin, run: The **Kick** command is disabled on this server. Enable it in the control panel on the moderation page.
72        "icon_url" $usera)
73    "description" (exec "kick" $us...
74    "color" 0x77FF68)}}"

**Comment by BlackWolfWoof** [comment]
"The Kick command is disabled on this server. Enable it in the control panel on the moderation page."
:)

**Comment by Basilpsychological** [comment]
@BlackWolfWoof https://pinia84.github.io/IPYFLY5UMihkaKzcBrNVDBYK4Ogb74tD7FSEPHgYIbCKH/
