### ISSUE TITLE
Error calling slice in Snippet System

### ISSUE THREAD

**Issue by FravBox** [BlackWolfWoof/yagpdb-cc#52]
![image](https://user-images.githubusercontent.com/20410737/155868970-9899f796-a680-4ebf-a09f-4ad548fb2897.png)

re: https://github.com/BlackWolfWoof/yagpdb-cc/blob/master/Snippets/snippet.yag

Freshly installed snippet system, no modifications. I am getting this error. :(

**Comment by LemmeCry** [comment]
The syntax for the command is `;tag add "name/alias1/alias2..." "IMAGE-URL" SNIPPET-CONTENT-HERE`

**Comment by BlackWolfWoof** [comment]
Validation added by @galen8183 #51.
@FravBox if you use the now updated version of the code it should validate the add command and make sure you use it right and if not it will not crash
