### ISSUE TITLE
Bot not working for link (MP4)

### ISSUE THREAD

**Issue by Piratealgeria** [BlackWolfWoof/yagpdb-cc#61]
Posted a video as an attachment and it worked fine
some else posted a video as a link (mp4) didn't work
![image](https://user-images.githubusercontent.com/45120897/200198917-6f6c635c-7fe7-4cfc-aa4d-328c224e0977.png)

my settings
[react.txt](https://github.com/BlackWolfWoof/yagpdb-cc/files/9946993/react.txt)

**Comment by Piratealgeria** [comment]
i assume it have something to do with the file name
![image](https://user-images.githubusercontent.com/45120897/200199029-76094b8a-5903-4826-be4e-e5285f09577f.png)

**Comment by Piratealgeria** [comment]
i assume it have something to do with the file name
![image](https://user-images.githubusercontent.com/45120897/200199068-84ccbd57-cac4-47b3-8ea5-6a42772495cf.png)

**Comment by BlackWolfWoof** [comment]
Can you check if you have the lastest version of the code?
There it should look for the embed type and not the file name.
If it is the latest version then try posting the link again, maybe it lagged and thats why it wasn't detected.
You can increase the sleep delay in the code (the seq 0 3) by setting it to seq 0 4 or 0 5, which makes the code slower but more consistent too.
