### ISSUE TITLE
Counting System is no longer functioning.

### ISSUE THREAD

**Issue by iamnottasweat** [BlackWolfWoof/yagpdb-cc#64]
I was previously using the system found on the YAGPDB CC GitHub but decided to switch to your counting system. It worked for a few hours, then the count went backwards ~100 and the system has since stopped working. I tested it via making a new discord server with a new channel, and your counting system worked without issue on the new server, but will not work on the original server I have it in. 

The command functionality is as follows:
• -setcount: **functional**
• -count: **non-functional** YAGPDB response is always "@user hasn't counted yet"
• -topcount: **non-functional** no YAGPDB response is received

**Comment by BlackWolfWoof** [comment]
The one on the yagpdb cc GitHub page is completely different from mine and none compatible

**Comment by iamnottasweat** [comment]
> The one on the yagpdb cc GitHub page is completely different from mine and none compatible

I did gather that from your repository and from comparing the two of them. I didn't attempt to stack them together at the same time. I disabled the YAGPDB CC GitHub system and added yours instead. It did work for hours, then suddenly stopped and hasn't worked since. Can I DM you on Discord instead?

**Comment by BlackWolfWoof** [comment]
The database entries that my system uses and the other system use are not the same, they are different and NOT compatible. You'd have to adjust either your database or my code to work with the other system.

**Comment by iamnottasweat** [comment]
I don't and didn't try to have it work with the other system. I am using only your system. The only counting system enabled on my server is yours.

**Comment by BlackWolfWoof** [comment]
If you want, message me on my server or the official yagpdb support server and i can join your server / check out your control panel and see if i can find the issue

**Comment by iamnottasweat** [comment]
Sounds good. I appreciate it greatly. I'll find you on the YAGPDB Support Server and DM you from there. Thank you!
